// <auto-generated />
using System;
using DevLearningHub.Api.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevLearningHub.Api.Migrations
{
    [DbContext(typeof(DevLearningHubContext))]
    [Migration("20260618090751_AddAllowedCopyToQuizSets")]
    partial class AddAllowedCopyToQuizSets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevLearningHub.Api.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ActorId", "CreatedAt" }, "idx_audit_logs_actor")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "TargetType", "TargetId" }, "idx_audit_logs_target");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_id");

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body_markdown");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("Downvotes")
                        .HasColumnType("int")
                        .HasColumnName("downvotes");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit")
                        .HasColumnName("is_accepted");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit")
                        .HasColumnName("is_hidden");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("post_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("Upvotes")
                        .HasColumnType("int")
                        .HasColumnName("upvotes");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex(new[] { "AuthorId" }, "idx_comments_author");

                    b.HasIndex(new[] { "PostId", "ParentId", "CreatedAt" }, "idx_comments_post");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.ModerationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("ModeratorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("moderator_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("ModeratorId");

                    b.ToTable("moderation_logs", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ref_id");

                    b.Property<string>("RefType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ref_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "IsRead", "CreatedAt" }, "idx_notif_user_unread")
                        .IsDescending(false, false, true);

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Module")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_permissions_name")
                        .IsUnique();

                    b.HasIndex(new[] { "Module" }, "idx_permissions_module");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid?>("AcceptedCommentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("accepted_comment_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_id");

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body_markdown");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("Downvotes")
                        .HasColumnType("int")
                        .HasColumnName("downvotes");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit")
                        .HasColumnName("is_hidden");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<int>("Upvotes")
                        .HasColumnType("int")
                        .HasColumnName("upvotes");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int")
                        .HasColumnName("view_count");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedCommentId");

                    b.HasIndex(new[] { "AuthorId", "CreatedAt" }, "idx_posts_author")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "IsHidden", "CreatedAt" }, "idx_posts_public_feed")
                        .IsDescending(false, true);

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("easy")
                        .HasColumnName("difficulty");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("StarterCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("starter_code");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("topic_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "TopicId", "Difficulty" }, "idx_problems_topic_diff");

                    b.ToTable("problems", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.ProgrammingLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Judge0LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("judge0_language_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Slug" }, "UQ_programming_languages_slug")
                        .IsUnique();

                    b.ToTable("programming_languages", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("explanation");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("beginner")
                        .HasColumnName("level");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("topic_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex(new[] { "TopicId", "Level" }, "idx_questions_topic_level");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("is_correct");

                    b.Property<byte>("OrderIndex")
                        .HasColumnType("tinyint")
                        .HasColumnName("order_index");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("question_id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.QuizAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("question_id");

                    b.Property<Guid?>("SelectedOptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("selected_option_id");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex(new[] { "SessionId" }, "idx_quiz_answers_session");

                    b.ToTable("quiz_answers", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.QuizSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("QuizSetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("quiz_set_id");

                    b.Property<short?>("Score")
                        .HasColumnType("smallint")
                        .HasColumnName("score");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("in_progress")
                        .HasColumnName("status");

                    b.Property<int?>("TimeTakenSeconds")
                        .HasColumnType("int")
                        .HasColumnName("time_taken_seconds");

                    b.Property<short>("TotalQuestions")
                        .HasColumnType("smallint")
                        .HasColumnName("total_questions");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("QuizSetId");

                    b.HasIndex(new[] { "UserId", "Status" }, "idx_sessions_user_status");

                    b.ToTable("quiz_sessions", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.QuizSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<bool>("AllowedCopy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("allowed_copy");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("level");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("practice")
                        .HasColumnName("mode");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("int")
                        .HasColumnName("time_limit_seconds");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<Guid?>("TopicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("topic_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TopicId");

                    b.ToTable("quiz_sets", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.QuizSetQuestion", b =>
                {
                    b.Property<Guid>("QuizSetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("quiz_set_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("question_id");

                    b.Property<short>("OrderIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("order_index");

                    b.HasKey("QuizSetId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("quiz_set_questions", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TokenHash" }, "idx_refresh_tokens_hash");

                    b.HasIndex(new[] { "UserId" }, "idx_refresh_tokens_user");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Roadmap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("level");

                    b.Property<short>("OrderIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("order_index");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("roadmaps", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.RoadmapTopic", b =>
                {
                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("roadmap_id");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("topic_id");

                    b.Property<short>("OrderIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("order_index");

                    b.HasKey("RoadmapId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("roadmap_topics", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_roles_name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("granted_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("code");

                    b.Property<string>("CompileOutput")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("compile_output");

                    b.Property<string>("Judge0Token")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("judge0_token");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("language");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("language_id");

                    b.Property<int?>("MemoryKb")
                        .HasColumnType("int")
                        .HasColumnName("memory_kb");

                    b.Property<short>("PassedCases")
                        .HasColumnType("smallint")
                        .HasColumnName("passed_cases");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("problem_id");

                    b.Property<int?>("RuntimeMs")
                        .HasColumnType("int")
                        .HasColumnName("runtime_ms");

                    b.Property<string>("Stderr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stderr");

                    b.Property<string>("Stdout")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stdout");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<short>("TotalCases")
                        .HasColumnType("smallint")
                        .HasColumnName("total_cases");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("verdict");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProblemId");

                    b.HasIndex(new[] { "UserId", "SubmittedAt" }, "idx_submissions_recent")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "UserId", "ProblemId" }, "idx_submissions_user_problem");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.SubmissionTestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("ActualOutput")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("actual_output");

                    b.Property<int?>("MemoryKb")
                        .HasColumnType("int")
                        .HasColumnName("memory_kb");

                    b.Property<int?>("RuntimeMs")
                        .HasColumnType("int")
                        .HasColumnName("runtime_ms");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("submission_id");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("test_case_id");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.HasIndex(new[] { "SubmissionId" }, "idx_str_submission");

                    b.ToTable("submission_test_results", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(7)
                        .HasColumnType("nchar(7)")
                        .HasDefaultValue("#6366f1")
                        .HasColumnName("color_hex")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_tags_name")
                        .IsUnique();

                    b.HasIndex(new[] { "Slug" }, "UQ_tags_slug")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("expected_output");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("input");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit")
                        .HasColumnName("is_hidden");

                    b.Property<short>("OrderIndex")
                        .HasColumnType("smallint")
                        .HasColumnName("order_index");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("problem_id");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.ToTable("test_cases", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_topics_name")
                        .IsUnique();

                    b.HasIndex(new[] { "Slug" }, "UQ_topics_slug")
                        .IsUnique();

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_locked");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("locked_reason");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.Property<int>("XpPoints")
                        .HasColumnType("int")
                        .HasColumnName("xp_points");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Email" }, "UQ_users_email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ_users_username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.UserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("granted_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("granted_by");

                    b.Property<bool>("IsGranted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_granted");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("GrantedBy");

                    b.HasIndex("PermissionId");

                    b.ToTable("user_permissions", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_by");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("AssignedBy");

                    b.HasIndex(new[] { "RoleId" }, "idx_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.UserTopicProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("topic_id");

                    b.Property<int?>("BestScore")
                        .HasColumnType("int")
                        .HasColumnName("best_score");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int")
                        .HasColumnName("correct_answers");

                    b.Property<DateTime?>("LastPracticedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_practiced_at");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("int")
                        .HasColumnName("total_attempts");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int")
                        .HasColumnName("total_questions");

                    b.HasKey("UserId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("user_topic_progress", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("target_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("VoteType")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("vote_type");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "TargetType", "TargetId" }, "UQ_votes_unique")
                        .IsUnique();

                    b.ToTable("votes", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.XpTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ref_id");

                    b.Property<string>("RefType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ref_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId", "CreatedAt" }, "idx_xp_user_recent")
                        .IsDescending(false, true);

                    b.ToTable("xp_transactions", (string)null);
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("post_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tag_id");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("post_tags", (string)null);
                });

            modelBuilder.Entity("ProblemTag", b =>
                {
                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tag_id");

                    b.HasKey("ProblemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("problem_tags", (string)null);
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.AuditLog", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.User", "Actor")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorId")
                        .IsRequired()
                        .HasConstraintName("FK_audit_logs_actor");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Comment", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_comments_author");

                    b.HasOne("DevLearningHub.Api.Entities.Comment", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_comments_parent");

                    b.HasOne("DevLearningHub.Api.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_comments_post");

                    b.Navigation("Author");

                    b.Navigation("Parent");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.ModerationLog", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.User", "Moderator")
                        .WithMany("ModerationLogs")
                        .HasForeignKey("ModeratorId")
                        .IsRequired()
                        .HasConstraintName("FK_moderation_logs_moderator");

                    b.Navigation("Moderator");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Notification", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_notifications_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Post", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.Comment", "AcceptedComment")
                        .WithMany("Posts")
                        .HasForeignKey("AcceptedCommentId")
                        .HasConstraintName("FK_posts_accepted_comment");

                    b.HasOne("DevLearningHub.Api.Entities.User", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK_posts_author");

                    b.Navigation("AcceptedComment");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Problem", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.User", "CreatedByNavigation")
                        .WithMany("Problems")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_problems_user");

                    b.HasOne("DevLearningHub.Api.Entities.Topic", "Topic")
                        .WithMany("Problems")
                        .HasForeignKey("TopicId")
                        .IsRequired()
                        .HasConstraintName("FK_problems_topic");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Question", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.User", "CreatedByNavigation")
                        .WithMany("Questions")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_questions_user");

                    b.HasOne("DevLearningHub.Api.Entities.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .IsRequired()
                        .HasConstraintName("FK_questions_topic");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.QuestionOption", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.Question", "Question")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_question_options_question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.QuizAnswer", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.Question", "Question")
                        .WithMany("QuizAnswers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_quiz_answers_question");

                    b.HasOne("DevLearningHub.Api.Entities.QuestionOption", "SelectedOption")
                        .WithMany("QuizAnswers")
                        .HasForeignKey("SelectedOptionId")
                        .HasConstraintName("FK_quiz_answers_option");

                    b.HasOne("DevLearningHub.Api.Entities.QuizSession", "Session")
                        .WithMany("QuizAnswers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_quiz_answers_session");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.QuizSession", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.QuizSet", "QuizSet")
                        .WithMany("QuizSessions")
                        .HasForeignKey("QuizSetId")
                        .IsRequired()
                        .HasConstraintName("FK_quiz_sessions_quiz_set");

                    b.HasOne("DevLearningHub.Api.Entities.User", "User")
                        .WithMany("QuizSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_quiz_sessions_user");

                    b.Navigation("QuizSet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.QuizSet", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.User", "CreatedByNavigation")
                        .WithMany("QuizSets")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_quiz_sets_user");

                    b.HasOne("DevLearningHub.Api.Entities.Topic", "Topic")
                        .WithMany("QuizSets")
                        .HasForeignKey("TopicId")
                        .HasConstraintName("FK_quiz_sets_topic");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.QuizSetQuestion", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.Question", "Question")
                        .WithMany("QuizSetQuestions")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_qsq_question");

                    b.HasOne("DevLearningHub.Api.Entities.QuizSet", "QuizSet")
                        .WithMany("QuizSetQuestions")
                        .HasForeignKey("QuizSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_qsq_quiz_set");

                    b.Navigation("Question");

                    b.Navigation("QuizSet");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.RefreshToken", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_refresh_tokens_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.RoadmapTopic", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.Roadmap", "Roadmap")
                        .WithMany("RoadmapTopics")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_roadmap_topics_roadmap");

                    b.HasOne("DevLearningHub.Api.Entities.Topic", "Topic")
                        .WithMany("RoadmapTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_roadmap_topics_topic");

                    b.Navigation("Roadmap");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.RolePermission", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_role_permissions_permission");

                    b.HasOne("DevLearningHub.Api.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_role_permissions_role");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Submission", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.ProgrammingLanguage", "LanguageNavigation")
                        .WithMany("Submissions")
                        .HasForeignKey("LanguageId")
                        .HasConstraintName("FK_submissions_lang");

                    b.HasOne("DevLearningHub.Api.Entities.Problem", "Problem")
                        .WithMany("Submissions")
                        .HasForeignKey("ProblemId")
                        .IsRequired()
                        .HasConstraintName("FK_submissions_problem");

                    b.HasOne("DevLearningHub.Api.Entities.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_submissions_user");

                    b.Navigation("LanguageNavigation");

                    b.Navigation("Problem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.SubmissionTestResult", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.Submission", "Submission")
                        .WithMany("SubmissionTestResults")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_str_submission");

                    b.HasOne("DevLearningHub.Api.Entities.TestCase", "TestCase")
                        .WithMany("SubmissionTestResults")
                        .HasForeignKey("TestCaseId")
                        .IsRequired()
                        .HasConstraintName("FK_str_test_case");

                    b.Navigation("Submission");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.TestCase", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.Problem", "Problem")
                        .WithMany("TestCases")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_test_cases_problem");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.UserPermission", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.User", "GrantedByNavigation")
                        .WithMany("UserPermissionGrantedByNavigations")
                        .HasForeignKey("GrantedBy")
                        .HasConstraintName("FK_user_permissions_granted_by");

                    b.HasOne("DevLearningHub.Api.Entities.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_permissions_permission");

                    b.HasOne("DevLearningHub.Api.Entities.User", "User")
                        .WithMany("UserPermissionUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_permissions_user");

                    b.Navigation("GrantedByNavigation");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.UserRole", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.User", "AssignedByNavigation")
                        .WithMany("UserRoleAssignedByNavigations")
                        .HasForeignKey("AssignedBy")
                        .HasConstraintName("FK_user_roles_assigned_by");

                    b.HasOne("DevLearningHub.Api.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_roles_role");

                    b.HasOne("DevLearningHub.Api.Entities.User", "User")
                        .WithMany("UserRoleUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_roles_user");

                    b.Navigation("AssignedByNavigation");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.UserTopicProgress", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.Topic", "Topic")
                        .WithMany("UserTopicProgresses")
                        .HasForeignKey("TopicId")
                        .IsRequired()
                        .HasConstraintName("FK_utp_topic");

                    b.HasOne("DevLearningHub.Api.Entities.User", "User")
                        .WithMany("UserTopicProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_utp_user");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Vote", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_votes_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.XpTransaction", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.User", "User")
                        .WithMany("XpTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_xp_transactions_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_post_tags_post");

                    b.HasOne("DevLearningHub.Api.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_post_tags_tag");
                });

            modelBuilder.Entity("ProblemTag", b =>
                {
                    b.HasOne("DevLearningHub.Api.Entities.Problem", null)
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_problem_tags_problem");

                    b.HasOne("DevLearningHub.Api.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_problem_tags_tag");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Comment", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Problem", b =>
                {
                    b.Navigation("Submissions");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.ProgrammingLanguage", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Question", b =>
                {
                    b.Navigation("QuestionOptions");

                    b.Navigation("QuizAnswers");

                    b.Navigation("QuizSetQuestions");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.QuestionOption", b =>
                {
                    b.Navigation("QuizAnswers");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.QuizSession", b =>
                {
                    b.Navigation("QuizAnswers");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.QuizSet", b =>
                {
                    b.Navigation("QuizSessions");

                    b.Navigation("QuizSetQuestions");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Roadmap", b =>
                {
                    b.Navigation("RoadmapTopics");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Submission", b =>
                {
                    b.Navigation("SubmissionTestResults");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.TestCase", b =>
                {
                    b.Navigation("SubmissionTestResults");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.Topic", b =>
                {
                    b.Navigation("Problems");

                    b.Navigation("Questions");

                    b.Navigation("QuizSets");

                    b.Navigation("RoadmapTopics");

                    b.Navigation("UserTopicProgresses");
                });

            modelBuilder.Entity("DevLearningHub.Api.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Comments");

                    b.Navigation("ModerationLogs");

                    b.Navigation("Notifications");

                    b.Navigation("Posts");

                    b.Navigation("Problems");

                    b.Navigation("Questions");

                    b.Navigation("QuizSessions");

                    b.Navigation("QuizSets");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Submissions");

                    b.Navigation("UserPermissionGrantedByNavigations");

                    b.Navigation("UserPermissionUsers");

                    b.Navigation("UserRoleAssignedByNavigations");

                    b.Navigation("UserRoleUsers");

                    b.Navigation("UserTopicProgresses");

                    b.Navigation("Votes");

                    b.Navigation("XpTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
